### ISSUE TITLE
Test Panel won't run with non-Oracle JRE on Windows 

### ISSUE THREAD

**Issue by rhodrie** [hapifhir/hapi-hl7v2#110]
Exception in thread "main" java.lang.UnsupportedOperationException: The ICON_IMAGE feature is not supported on the current platform!
        at java.desktop/java.awt.Taskbar.checkFeatureSupport(Unknown Source)
        at java.desktop/java.awt.Taskbar.setIconImage(Unknown Source)
        at ca.uhn.hl7v2.testpanel.OSXInitializer.run(OSXInitializer.java:47)
        at ca.uhn.hl7v2.testpanel.App.main(App.java:65)

This, for example, is using Eclipse Temurin v 21

**Comment by subigre** [comment]
Same issue here, the application works like a charm on MacOS using Temurin 17 JDK.
However, on Windows, I tried the following JDK without success:
- Temurin 11, 17 and 21
- OpenJDK 17
- Oracle JDK 17

**Comment by rhodrie** [comment]
Fixed in release 2.6.0.  (Test Panel runs successfully on Microsoft Build of OpenJDK.)

**Comment by subigre** [comment]
Thank you
