### ISSUE TITLE
Exception in the startup the testpanel

### ISSUE THREAD

**Issue by isuruuy429** [hapifhir/hapi-hl7v2#112]
## Description

Getting the following exception in the startup. 
```
isuruuy:hapi-testpanel-2.5.1 isuruuy$ ./testpanel.sh
11:21:23,673  INFO [main] Home:47 - hapi.home is set to /Users/isuruuy/Downloads/hapi-testpanel-2.5.1/.
11:21:24,304  INFO [main] Controller:133 - Restoring work files from directory: /Users/isuruuy/HapiTestPanel/workfiles
11:21:24,304  INFO [main] MessagesList:174 - Restoring work file: c2493a7e-e4d0-4dde-87b9-e86c308845fb-0000000001.xml
11:21:24,355  INFO [main] VersionLogger:75 - HAPI version is: 2.5.1
11:21:24,359  INFO [main] VersionLogger:65 - Default Structure libraries found for HL7 versions 2.1, 2.2, 2.3, 2.3.1, 2.4, 2.5, 2.5.1, 2.6, 2.7, 2.8, 2.8.1, 
11:21:24,380  INFO [main] Hl7V2MessageCollection:899 - About to set source message for collection
11:21:24,381  INFO [main] Hl7V2MessageCollection:277 - Found ER7 message
11:21:24,383  INFO [main] Hl7V2MessageBase:256 - About to parse message
11:21:24,441  INFO [main] Hl7V2MessageBase:272 - Done parsing message
11:21:24,444  INFO [main] Hl7V2MessageCollection:916 - Firing message change event
11:21:24,445  INFO [main] Hl7V2MessageCollection:927 - Done setting source message for collection
11:21:24,445  INFO [main] MessagesList:174 - Restoring work file: de6a14c5-a41b-4ad1-afad-d8f2e3d9cd30-0000000002.xml
11:21:24,450  INFO [main] Hl7V2MessageCollection:899 - About to set source message for collection
11:21:24,450  INFO [main] Hl7V2MessageCollection:916 - Firing message change event
11:21:24,450  INFO [main] Hl7V2MessageCollection:927 - Done setting source message for collection
11:21:24,450  INFO [main] Hl7V2MessageCollection:899 - About to set source message for collection
11:21:24,452  INFO [main] Hl7V2MessageCollection:277 - Found ER7 message
11:21:24,452  INFO [main] Hl7V2MessageBase:256 - About to parse message
11:21:24,499  INFO [main] Hl7V2MessageBase:272 - Done parsing message
11:21:24,499  INFO [main] Hl7V2MessageCollection:916 - Firing message change event
11:21:24,499  INFO [main] Hl7V2MessageCollection:927 - Done setting source message for collection
11:21:24,499  INFO [main] MessagesList:174 - Restoring work file: 6f52bf89-757a-4052-b0c4-01f793e20e8b-0000000003.xml
11:21:24,502  INFO [main] Hl7V2MessageCollection:899 - About to set source message for collection
11:21:24,502  INFO [main] Hl7V2MessageCollection:277 - Found ER7 message
11:21:24,503  INFO [main] Hl7V2MessageBase:256 - About to parse message
11:21:24,546  INFO [main] Hl7V2MessageBase:272 - Done parsing message
11:21:24,547  INFO [main] Hl7V2MessageCollection:916 - Firing message change event
11:21:24,547  INFO [main] Hl7V2MessageCollection:927 - Done setting source message for collection
11:21:24,547  INFO [main] MessagesList:174 - Restoring work file: b9833503-e025-47a4-9229-3e2f01415eb5-0000000004.xml
11:21:24,551  INFO [main] Hl7V2MessageCollection:899 - About to set source message for collection
11:21:24,551  INFO [main] Hl7V2MessageCollection:916 - Firing message change event
11:21:24,551  INFO [main] Hl7V2MessageCollection:927 - Done setting source message for collection
11:21:24,552  INFO [main] Hl7V2MessageCollection:899 - About to set source message for collection
11:21:24,553  INFO [main] Hl7V2MessageCollection:916 - Firing message change event
11:21:24,553  INFO [main] Hl7V2MessageCollection:927 - Done setting source message for collection
11:21:24,579  INFO [main] Controller:151 - No saved outbound connection list found
11:21:25,748  INFO [AWT-EventQueue-0] Controller:885 - Starting TestPanel Controller...
11:21:25,941  INFO [AWT-EventQueue-0] TestPanelWindow:173 - Restoring window size to java.awt.Dimension[width=1176,height=718] and location to java.awt.Point[x=210,y=100]
11:21:25,942  WARN [AWT-EventQueue-0] TestPanelWindow:135 - Unknown type is selected: null
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
11:21:26,630  INFO [AWT-EventQueue-0] Hl7V2MessageEditorPanel:119 - Registered syntaxKit
java.lang.NullPointerException
	at ca.uhn.hl7v2.testpanel.ui.editor.Hl7V2MessageEditorPanel.setMessage(Hl7V2MessageEditorPanel.java:709)
	at ca.uhn.hl7v2.testpanel.controller.Controller.setLeftSelectedItem(Controller.java:815)
	at ca.uhn.hl7v2.testpanel.controller.Controller.start(Controller.java:908)
	at ca.uhn.hl7v2.testpanel.App.lambda$main$0(App.java:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


```

Once trying to generate a message, getting this error. 
<img width="1465" alt="Screenshot 2023-12-22 at 11 19 05" src="https://github.com/hapifhir/hapi-hl7v2/assets/31693103/b6db1711-4cf2-4cd2-ae48-4ca0b1872a4f">

## Environment tested
macOS
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

This has been a blocker for us. Kindly assist.

**Comment by winfriedgerlach** [comment]
@isuruuy429 does the problem persist with HAPI TestPanel 2.6.0? If not, could you pls close this issue?
