### ISSUE TITLE
HL7v2 - Cannot configure MLLP client connection timeout, when created from DefaultHapiContext

### ISSUE THREAD

**Issue by patrick-vachon-smilecdr** [hapifhir/hapi-hl7v2#126]
On Hapi-base 2.5.1
When using ca.uhn.hl7v2.DefaultHapiContext.newClient(), it ends up creating a Socket that is not using a connection timeout:
```
	at ca.uhn.hl7v2.app.ConnectionFactory.createSocket(ConnectionFactory.java:77)
	at ca.uhn.hl7v2.app.ConnectionFactory.openEagerly(ConnectionFactory.java:53)
	at ca.uhn.hl7v2.app.ConnectionFactory.open(ConnectionFactory.java:44)
	at ca.uhn.hl7v2.app.ConnectionHub$1.open(ConnectionHub.java:99)
	at ca.uhn.hl7v2.app.ConnectionHub$1.open(ConnectionHub.java:85)
	at ca.uhn.hl7v2.app.ConnectionHub$CountingMap.put(ConnectionHub.java:489)
	at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:121)
	at ca.uhn.hl7v2.app.ConnectionHub.attach(ConnectionHub.java:260)
	at ca.uhn.hl7v2.DefaultHapiContext.newClient(DefaultHapiContext.java:335)
```

It would be great to be able to configure it somehow, easily.
```
class ConnectionFactory
    ...
    private static Socket createSocket(ca.uhn.hl7v2.util.SocketFactory socketFactory, String host, int port, boolean tls)
        throws IOException {
        Socket socket;
        if (tls) {
            socket = socketFactory.createTlsSocket();
        } else {
            socket = socketFactory.createSocket();
        }
->      socket.connect(new InetSocketAddress(host, port));
        return socket;
    }
```
as Socket has a connect() method on which we can pass a connection timeout.
May be it could be added in ca.uhn.hl7v2.util.SocketFactory and used with the appropriate Socket.connect()?

Was found with 
```
        <dependency>
            <groupId>ca.uhn.hapi</groupId>
            <artifactId>hapi-structures-v24</artifactId>
            <version>2.5.1</version>
        </dependency>
```

Culprit code on master:
https://github.com/hapifhir/hapi-hl7v2/blob/master/hapi-base/src/main/java/ca/uhn/hl7v2/app/ConnectionFactory.java

Thanks!

**Comment by michaelabuckley** [comment]
If you add a timeout to the ConnectionData, you could configure it when building the ConnectionHub.  That is passed all the way down to the ConnectionFactory.

**Comment by TomasLukl** [comment]
@michaelabuckley I do not think this will work. ConnectionData is private and its connectionTimeout field is not used - see ConnectionFactory.createSocket method, where socket.connect is called without any timeout. This means that connecting to a remote HL7v2 server will wait indefinitely (in theory).
Can this be fixed please?

**Comment by patrick-vachon-smilecdr** [comment]
I tend to agree, the only way to fix that correctly is to call
```
socket.connect(new InetSocketAddress(host, port), theTimeout);
```

https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#connect-java.net.SocketAddress-int-

That was the only way we found, while working on my current project.
