### ISSUE TITLE
Decoder Exeption

### ISSUE THREAD

**Issue by Pravin1965** [hapifhir/hapi-hl7v2#128]
ca.uhn.hl7v2.hoh.api.DecodeException: Invalid response line, no space after status code. Line is: HTTP/1.1 400
        at ca.uhn.hl7v2.hoh.encoder.Hl7OverHttpResponseDecoder.readActionLineAndDecode(Hl7OverHttpResponseDecoder.java:32)
        at ca.uhn.hl7v2.hoh.encoder.AbstractHl7OverHttpDecoder.readHeadersAndContentsFromInputStreamAndDecode(AbstractHl7OverHttpDecoder.java:514)
        at ca.uhn.hl7v2.hoh.raw.client.AbstractRawClient.doSendAndReceiveInternal(AbstractRawClient.java:159)
        at ca.uhn.hl7v2.hoh.raw.client.AbstractRawClient.sendAndReceive(AbstractRawClient.java:279)
        at ca.uhn.hl7v2.hoh.raw.client.HohRawClientSimple.sendAndReceive(HohRawClientSimple.java:55)
        at ca.uhn.hl7v2.hoh.hapi.client.AbstractClient.sendAndReceiveMessage(AbstractClient.java:161)

**Comment by winfriedgerlach** [comment]
sounds like a duplicate of #17
