### ISSUE TITLE
Testpanel fails to launch on Java 11

### ISSUE THREAD

**Issue by nordfalk** [hapifhir/hapi-hl7v2#59]
$ java -jar hapi-testpanel-2.3-jar-with-dependencies.jar

16:50:51,619  INFO [main] Home:47 - hapi.home is set to /home/j/Hentet/hapi-testpanel-2.3/.
Gtk-Message: 16:50:51.906: Failed to load module "canberra-gtk-module"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at ca.uhn.hl7v2.testpanel.App.main(App.java:60)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more

This is because it needs to be recompiled to Java 11, I think.

**Comment by nordfalk** [comment]
I am using newest release from https://github.com/hapifhir/hapi-hl7v2/releases

**Comment by michaelgarde** [comment]
I managed to workaround this, by manually adding the missing dependencies to the classpath. By adding 

- javax.activation-api-1.2.0.jar
- jaxb-impl-2.3.6.jar
- jaxb-core-2.3.0.1.jar
- jaxb-api-2.3.1.jar

I managed to launch TestPanel with

`java -Djavax.net.debug=ssl,handshake -cp "hapi-testpanel-2.3-jar-with-dependencies.jar;lib/jaxb-api-2.3.1.jar;lib/jaxb-core-2.3.0.1.jar;lib/jaxb-impl-2.3.6.jar;lib/javax.activation-api-1.2.0.jar" ca.uhn.hl7v2.testpanel.App`
