### ISSUE TITLE
Xml parsing fails if xml message has several namespaces and urn:hl7-org:v2xml is not the first

### ISSUE THREAD

**Issue by hannukotipalo** [hapifhir/hapi-hl7v2#65]
The problem appeared when we updated the library from ver 2.1 to 2.3

Unit test to reveal the problem:
------------------------
    private boolean isPipeAndHat = false;
    private static final String testMsg = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<ACK xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns=\"urn:hl7-org:v2xml\">\n" +
            "  <MSH>\n" +
            "    <MSH.1>|</MSH.1>\n" +
            "    <MSH.2>^~\\&amp;</MSH.2>\n" +
            "    <MSH.3>\n" +
            "      <HD.1/>\n" +
            "    </MSH.3>\n" +
            "    <MSH.4>\n" +
            "      <HD.1/>\n" +
            "    </MSH.4>\n" +
            "    <MSH.5>\n" +
            "      <HD.1/>\n" +
            "    </MSH.5>\n" +
            "    <MSH.6>\n" +
            "      <HD.1/>\n" +
            "    </MSH.6>\n" +
            "    <MSH.7>\n" +
            "      <TS.1>20210525111033.506+0200</TS.1>\n" +
            "    </MSH.7>\n" +
            "    <MSH.9>\n" +
            "      <CM_MSG.1>ACK</CM_MSG.1>\n" +
            "      <CM_MSG.2/>\n" +
            "    </MSH.9>\n" +
            "    <MSH.10>396990</MSH.10>\n" +
            "    <MSH.11>\n" +
            "      <PT.1>D</PT.1>\n" +
            "    </MSH.11>\n" +
            "    <MSH.12>2.3</MSH.12>\n" +
            "    <MSH.13/>\n" +
            "  </MSH>\n" +
            "  <MSA>\n" +
            "    <MSA.1>AA</MSA.1>\n" +
            "    <MSA.2>396990</MSA.2>\n" +
            "    <MSA.3>The Observation message has been saved successfully.</MSA.3>\n" +
            "    <MSA.4/>\n" +
            "    <MSA.5/>\n" +
            "    <MSA.6>\n" +
            "      <CE_0357>\n" +
            "        <CE_0357.1/>\n" +
            "        <CE_0357.2>The Observation message has been saved successfully.</CE_0357.2>\n" +
            "        <CE_0357.3/>\n" +
            "        <CE_0357.4/>\n" +
            "        <CE_0357.5/>\n" +
            "        <CE_0357.6/>\n" +
            "      </CE_0357>\n" +
            "    </MSA.6>\n" +
            "  </MSA>\n" +
            "</ACK>\n";

    @Test
    void testParser() {
        GenericParser myParser = null;
        LOG.info("new GenericParser()");
        myParser = new GenericParser();
        if (isPipeAndHat) {
            LOG.info("setPipeParserAsPrimary()");
            myParser.setPipeParserAsPrimary();
        } else {
            LOG.info("setXMLParserAsPrimary()");
            myParser.setXMLParserAsPrimary();
        }
        try {
            LOG.info("Parsing "+testMsg);
            parser.parse(testMsg);
            LOG.info("Parsing done");
        } catch (Exception e) {
            LOG.info("Parser error",e);
            fail();
        }
    }
---------------
Looks like the buggy code is on 
https://github.com/hapifhir/hapi-hl7v2/blob/v2.3/hapi-base/src/main/java/ca/uhn/hl7v2/parser/XMLParser.java
lines 755 - 762.

**Comment by hannukotipalo** [comment]
Exception will be:
-------------
 Exception in endpoint call!!
ca.uhn.hl7v2.HL7Exception: Couldn't find MSH.12 in message beginning: <?xml version="1.0" encoding="utf-8"?><ACK xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="u
	at ca.uhn.hl7v2.parser.XMLParser.parseLeaf(XMLParser.java:775)
	at ca.uhn.hl7v2.parser.XMLParser.getVersion(XMLParser.java:732)
	at ca.uhn.hl7v2.parser.GenericParser.getVersion(GenericParser.java:191)
	at ca.uhn.hl7v2.parser.Parser.parse(Parser.java:205)
	at ca.uhn.hl7v2.parser.GenericParser.parse(GenericParser.java:253)
	at

**Comment by hannukotipalo** [comment]
Test will pass with this trick:
        String ver_2_3_LibraryFixedString = testMsg.replace(
                "<ACK xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns=\"urn:hl7-org:v2xml\">",
                "<ACK xmlns=\"urn:hl7-org:v2xml\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">"
                );
        parser.parse(ver_2_3_LibraryFixedString);

**Comment by ccn974** [comment]
Change `NS_PATTERN `constant `Pattern.compile("xmlns(.*)=\"" + NS + "\"")` to `Pattern.compile("xmlns([^=]*)=\"" + NS + "\"")` fixes this bug
